
[[override]]
  name = "github.com/jmoiron/sqlx"
  version = "v1.2.0"

[[override]]
  name = "github.com/lib/pq"
  version = "v1.2.0"

[[override]]
  name = "go.uber.org/zap"
  version = "1.9.1"
  
[[override]]
  name = "github.com/appleboy/gin-jwt"
  revision = "1f7b3e975316d42a886d504284c2a42768b8d0f7"
