version: 2.1
orbs:
  gcr: circleci/gcp-gcr@0.6.1
jobs:
  build_staging:
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: incognito-data-sync
          tag: $(echo $CIRCLE_SHA1 | cut -c -7)
          dockerfile: staging.Dockerfile
          extra_build_args: --build-arg API_CONF_DATA
      - gcr/push-image:
          image: incognito-data-sync
          tag: $(echo $CIRCLE_SHA1 | cut -c -7)
  deploy_staging:
    docker:
      - image: gcr.io/staging-incognito/deployer:0.3
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
        environment:
          CLUSTER: staging
          RELEASE: incognito-data-sync
          PROJECT: staging-incognito
          NAMESPACE: default
    working_directory: /etc/deployments
    steps:
      - run: bash deploy.sh
workflows:
  version: 2
  deploy_staging:
    jobs:
      - build_staging:
          filters:
            branches:
              only:
                - develop
      - deploy_staging:
          requires:
            - build_staging
